baseURL = "http://www.avalonhoasc.com"
languageCode = "en-us"
title = "Avalon"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 1720689101561189 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
publishDir = "docs"

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Welcome to our community."
  facebook = "https://www.facebook.com/groups/1720689101561189/"
  instagram = ""
  github = "https://github.com/paperTurkey/hoamaster"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-silver"
  featured_image = "/images/avalonfront.jpg"
  recent_posts_number = 4
